### ISSUE TITLE
it dont have money drop

### ISSUE THREAD

**Issue by hackertr44** [HatchesPls/GrandTheftAutoV-Cheat#12]
Can you add money drop or recovery money change :)

**Comment by HatchesPls** [comment]
Money drops (created using CREATE_AMBIENT_PICKUP) have been detected for a while now (regardless of use rate), therefor it was removed with version 2.1 (October last year). I have not explored other methods of creating a 'money drop' (yet).

**Comment by hackertr44** [comment]
So can You add money cheat? i want add money

**Comment by iAmChump** [comment]
@hackertr44 https://i.imgur.com/m4vZ067.png , (yet) .....be patient :D ,
