### ISSUE TITLE
Hello, dear author. I have some questions and even cooperation. Can I leave a contact information?

### ISSUE THREAD

**Issue by LvTu621** [HatchesPls/GrandTheftAutoV-Cheat#13]
Hello, dear author. I have some questions and even cooperation. Can I leave a contact information?

**Comment by HatchesPls** [comment]
As this is a open source project and to ensure full transparency I prefer to discuss any matters related to this project publicly on GitHub. But if you do insist, you can also contact me on hatchespls@protonmail.com or through a DM on [Twitter](https://twitter.com/hatchespls).
