### ISSUE TITLE
Vehicle Images not lined up with array, not sure if this is where im supposed to put this, haha 

### ISSUE THREAD

**Issue by iAmChump** [HatchesPls/GrandTheftAutoV-Cheat#14]
line switch , im sure woulda been figured out by you adventually :) lol im as nooob as it gets lmao , 

in source , GUI::VehicleOption

just change 

this:

        bool OnCurrent = GUI::currentOption == GUI::optionCount ? true : false;
	if (Option(option, ""))
	{
		return true;
	}
	if (OnCurrent)
	{

to this:

	if (Option(option, ""))
	{
		return true;
	}
	bool OnCurrent = GUI::currentOption == GUI::optionCount ? true : false;
	if (OnCurrent)
	{

it sets the array of images correctly with vehicles your previewing,

**Comment by HatchesPls** [comment]
Thank you! I have tried to figure out that issue for quite some time now but evidently completely missed the position of that boolean. Just pushed d17534ab617300df3980d974496093fff1627679 fixing it. I will be sure to credit you in the release notes of the next release build.

**Comment by iAmChump** [comment]
no worries at all such a small small issue, i spent days on it cause im a noob hahaa it was driving me mental lmaooo :D Love the menu brotha, an the ui., im very new like really new hahaha , infact im just starting a basic c++ college course in june, im 34 ,, started a little late but i enjoy modding games, so figured id start going to school for what i like. never to late to learn something new  :D thanks again for the release bro :D have a great day !!
