### ISSUE TITLE
GTAV 1.59 UPDATE

### ISSUE THREAD

**Issue by iAmChump** [HatchesPls/GrandTheftAutoV-Cheat#15]
There has been an update to gta. but crossmaps an sigs seem to be fine, globals have had some changes unfortunetly ,, here is what i have found so far. join online session join friend, join solo ect, those globals have changed but have yet to find em , 

Off Radar
2689224, *PID*, 451, 207
2703660, 56

Cops Blind / Bribe
2810701, 4624
2810701, 4627

Easy Way Out Cooldown
262145, 28073
262145, 28074

Global Requests
BULLSHARK = 2703660, 3576

Wallet Money
1853131, *PID*, 888, 205, 3
Total Money
1853131, *PID*, 888, 205, 56
KD Ratio
1853131, *PID*, 888, 205, 26
Rank
1853131, *PID*, 888, 205, 6

**Comment by HatchesPls** [comment]
Awesome! Working on it right now, expecting to have a update out in around 2 hours.

**Comment by HatchesPls** [comment]
Version 2.1.0.5 released. See Releases.

**Comment by iAmChump** [comment]
jessus christ bro lol i went grocery shopping an you updated before i got back in hahaha this man is a OG people, literally proper stuff mate, :D glad ive found this git, u sir are a bruv my guy
