### ISSUE TITLE
why is the release and the main version so different and why does it missing features?

### ISSUE THREAD

**Issue by deepdev237** [HatchesPls/GrandTheftAutoV-Cheat#20]
the online and teleport menus are completely different
and the teleport instantly teleports you to somewhere(i guess where your mouse was)

**Comment by deepdev237** [comment]
why can't i teleport to players or do anything related to other players?

**Comment by deepdev237** [comment]
or this is only in the stable version? sorry i just dont understand this whole thing

**Comment by deepdev237** [comment]
the misc menu promps you to enter a number

**Comment by deepdev237** [comment]
Why are the two versions so different?

**Comment by HatchesPls** [comment]
> Why are the two versions so different?

Main branch is under development and contains significant changes (primary being Dear ImGui introduction) set for v2.2.0.0 release. v2.1.0.6 is currently stable, if you want the source code for the stable version download it from the Releases section.

> why can't i teleport to players or do anything related to other players?
Teleporting to players or doing other player related actions means you need to navigate to Online -> Players > [Player name].

**Comment by deepdev237** [comment]
> Teleporting to players or doing other player related actions means you need to navigate to Online -> Players > [Player name].
Online opens the Session menu

**Comment by deepdev237** [comment]
Only Vehicle, Settings and Spawn opens the right menu

**Comment by HatchesPls** [comment]
> Only Vehicle, Settings and Spawn opens the right menu

Are you using the [compiled latest stable version](https://github.com/HatchesPls/GrandTheftAutoV-Cheat/releases/tag/v2.1.0.6) when experiencing this issue?

**Comment by deepdev237** [comment]
No, i just thought the main version would have more, just beta features and not less, but the ImGui introduction explains that.
Thank you
