### ISSUE TITLE
Issue with compiling

### ISSUE THREAD

**Issue by dripgotthatdrip** [HatchesPls/GrandTheftAutoV-Cheat#23]
Hello, so when compiling i get an error about some std string, it is already #included but still doesn't want to work, do i need to install anything else with the source or?

**Comment by HatchesPls** [comment]
You don't. Can you provide the exact error you receive?

**Comment by dripgotthatdrip** [comment]
I accidentally had gui.h open and that was the one throwing up errors, fixed it now, sorry for the inconvenience.
