### ISSUE TITLE
How to add code through github to your source?

### ISSUE THREAD

**Issue by iAmChump** [HatchesPls/GrandTheftAutoV-Cheat#24]
Hey bro, so I worked on a few things last night mainly Give vehicle. Its messssssy as fuck as im still learning the basics, literally, still copy alot of code an edit it to work with your menu (skid shit) I kno , but im a 34 year old skid who just jumped into this mess a few years back when ps3 came out i made a c# tool. an thought hey lets just jump right into f*ckin c++ lmaooo dumbass move but hey i wanna learn, so anyways, how does one share with you what ive added, ive managed to get give vehicle to work from anywhere on map an you dont need to be close as far as ive tested. , i would like to share with you so that if u like to u can add it to source, its working an fully tested online, an uses your native code, so youll be able to edit it to some super sexyness like u do hahah, its pretty basic an i had to dupe alot of shit cause thats the noob shit i know lmao im sure youll be able to make it alot sexier hahaha, but yea, how does one share code to you ? lol

**Comment by HatchesPls** [comment]
That's awesome! Sharing is probably the easiest by committing the change to your forked version of this repository and then create a Pull Request.

**Comment by iAmChump** [comment]
thanks dude :D ill do my best may take me a little to learn how to do that but ill watch some youtube tuts an see if i can learn hahaha, also, i noticed some weird shit happening with the criminal enterprises DLC , some cars (most) cars kick u in single player an online, is there some sort of new online vehicle bypass an offline bypass, cause even with offline bypass these cars once spawned still despawn , 10f, weevil , ect, there a few that do spawn an stay but most dont, so strange , also. ive been working on a unload for so fucking long lmaoo, is there a way your testing your menu after injection without having to keep restarting gta an  reinjecting  im gonna keep trying to get the unload fixed, i have a bigbase V1 unload that is so similar to your unload i feel its something so small thats gotta be fixed , but im not 100 percent, lol , also u got discord ? would be cool as fuck to have you as a mentor kinda thing, since im in love with your menu an have learned how disgusting other code is written in other sources after seeing your majestic written sexyness hahahahahahahahhaha if u would like add me up iAmChump#3246

**Comment by iAmChump** [comment]
I almost forgot, I made you a few headers, cant seem to find the other 2 , but ill look thru my folders an adventually find them hahaha, there 3 different styles, heres the first one i could find hahaha

https://i.imgur.com/OmzYhBE.png

**Comment by HatchesPls** [comment]
> thanks dude :D ill do my best may take me a little to learn how to do that but ill watch some youtube tuts an see if i can learn hahaha, also, i noticed some weird shit happening with the criminal enterprises DLC , some cars (most) cars kick u in single player an online, is there some sort of new online vehicle bypass an offline bypass, cause even with offline bypass these cars once spawned still despawn , 10f, weevil , ect, there a few that do spawn an stay but most dont, so strange , also. ive been working on a unload for so fucking long lmaoo, is there a way your testing your menu after injection without having to keep restarting gta an reinjecting im gonna keep trying to get the unload fixed, i have a bigbase V1 unload that is so similar to your unload i feel its something so small thats gotta be fixed , but im not 100 percent, lol , also u got discord ? would be cool as fuck to have you as a mentor kinda thing, since im in love with your menu an have learned how disgusting other code is written in other sources after seeing your majestic written sexyness hahahahahahahahhaha if u would like add me up iAmChump#3246

There is game logic introduced with the latest update that despawns the latest unreleased DLC vehicles, matter of time before they are all out and this issue will fix itself. The main branch has the SP spawn bypass fixed so they should spawn in Single Player successfully now (and not despawn).

Unloading the cheat is currently experimental and disabled in latest release because of the addition of ImGui (and all things that requires). I already have and need to spend a lot more time to get that properly working, it's quite complex; you essentially need to restore any memory modification by the cheat in the game process to the state it was before the cheat was injected.

Due to limited time I'm unfortunately not able to help you on anything outside of this project, for that reason I prefer keeping all communication through this repository for future reference and because it is open source.

That header looks great, I don't think I would want that header (or anything else) to be available standard but I do want to make a feature in which you can easily load a custom YTD/texture file with custom headers, toggles and icons.

**Comment by HatchesPls** [comment]
> im going to figure out how to send the stuff i added cause i added gif support an a few other things ill send an show ya ,

Great! Added a toggle (ccd002a4fdad5e767933120465c83043413668ca) to prevent the texture file from being overwritten, you can now put a custom texture file in the data directory to load custom textures.
![Image](https://i.ibb.co/1nVwhSF/ss.png)

**Comment by iAmChump** [comment]
Bro, that's such a good idea, so now u can just put in a image in the folder an it will pull the image you have set in the folder ? if so ,absolutely genius bro, love it, Love the header to ;)  where'd you get that sexiness' from? lolol also, im doing a thing, its a lonnnng ass tedious thing hahah but i think its going to look absolutely amazing with this source, ive basically taken what you did with the vehicle preview images, set it to ped's an resized the box to fit the Peds/animals., so ive got about 130/140 done so far, but theres i believe 900+ but i will do them all. So we can have character model so the peds in a preview window like vehicles so people can see which ped is which rather them fmy_beach_bum ect. also can be added when u decide to add Spawn ped manager, ive got a wicked source that allows for once u spawn a ped, controlling it, ie, getting in a spawned vehicle, following you in the vehicle, ect,. its decent i can prolly get it to work for the ped spawner an we would have a fucking cool as preview box for the ped spawner an model options, something so simple but will make it that much more user friendly,

**Comment by iAmChump** [comment]
https://i.imgur.com/fVGUxKI.png

**Comment by iAmChump** [comment]
I will Complete them all, Even if it takes till Next year hahahaha, but i think it will look awesome,
