### ISSUE TITLE
encountered a problem adding external json

### ISSUE THREAD

**Issue by MaxDamon** [HatchesPls/GrandTheftAutoV-Cheat#31]
![P~YAN4 J8%7@$ZD2XU1LK L](https://user-images.githubusercontent.com/121487088/209646269-2d2227d5-0c0c-4019-a568-ad1907607ad2.jpg)
As you can see I want to do text substitution via an external json file, i.e., multiple languages.
I added other languages in a separate Home page, which is feasible, but I don't know how to replace in real time in the game, or in Settings to iterate through other json files, click to replace, is there anything that can be optimized or something else, sorry I'm new to this, maybe this can only be a good idea.

**Comment by HatchesPls** [comment]
What you have shown seems to be working fine. 

I won't be able to help you with or implement such functionality right now as I'm currently working on cleaning up and restructuring the project in various ways but I have seen requests about multi-language support before and I definitely want to look into this further in the future.

**Comment by MaxDamon** [comment]
thx u for all
