### ISSUE TITLE
Error to compile

### ISSUE THREAD

**Issue by justgabriell** [HatchesPls/GrandTheftAutoV-Cheat#33]
Hello! I have some problems compiling the DLL, I already installed MFC in visual studio 22 and 19 and I still can't, I changed it to Stantard windows libraries and it solves the MFC problem but it creates several other problems.

Please, help me ;(

![image](https://user-images.githubusercontent.com/104325139/209872970-214adeb5-bb0c-4a41-84f1-f46b92f391ff.png)

**Comment by HatchesPls** [comment]
For VS 2022, make sure the "C++ v14.34 (17.4) MFC for v143 build tools (x86 & x64)" component is installed. In the VS Project properties, make sure that Platform Toolset is set correctly under General.
