### ISSUE TITLE
Entity MT Freeze

### ISSUE THREAD

**Issue by iAmChump** [HatchesPls/GrandTheftAutoV-Cheat#34]
Just a lil bug i havent looked into yet but,  the entity MT or NT  causes a crash on Max Upgrade.

**Comment by HatchesPls** [comment]
Bug confirmed. Investigating and implementing a fix soon.

**Comment by HatchesPls** [comment]
Hotfixed in 9e55e4b756739ef55e1d5ed3024f3686f2208fb0. Certain DLC vehicles now can't get max upgraded using this feature.
