### ISSUE TITLE
Build solution issue. 

### ISSUE THREAD

**Issue by iAmChump** [HatchesPls/GrandTheftAutoV-Cheat#35]
https://i.imgur.com/RYrKUtU.png
https://i.imgur.com/VT8UTet.png

what did i fu*k up ? 

I literally just downloaded the newest version loaded into vs,2022 , an built, an all those errors showed, but the last version before this one loads perfectly fine, I cant figure out what the hell I did wrong

**Comment by iAmChump** [comment]
I think i figured it out , all the vendor files are empty , i think there missing from the source download.

**Comment by HatchesPls** [comment]
Download it using `git clone --recursive https://github.com/HatchesPls/GrandTheftAutoV-Cheat` to ensure all vendor packages are downloaded as well. Don't forget to `checkout` (see the README) a specific release unless you want to use the latest `main` branch (development).

**Comment by HatchesPls** [comment]
Pushed 02056aa665d084758d860076126b6d906cedde18 to `main` which corrects many of the includes paths, this might fix any issues with this if you still had them after cloning the repository as mentioned earlier.

**Comment by iAmChump** [comment]
flawless bro  https://i.imgur.com/6Hp67Wj.png  thank you, Im still a super noob bahahhaa so lil errors destroy me sometimes hahahahah i was legit stuck bro thank u
i have a question i want to ask you but i dont want to ask you on here so someone can steal my idea hahahahaha, can i email u?

**Comment by HatchesPls** [comment]
Things directly related to this project should be discussed on Github exclusively but you can reach me on [hatchespls@protonmail.com](mailto:hatchespls@protonmail.com).

**Comment by HatchesPls** [comment]
On a closing note; as this Repository is gaining a bit of traction recently and Issues have been getting misused to ask setup (usually user-error) related questions I have enabled [Discussions](https://github.com/HatchesPls/GrandTheftAutoV-Cheat/discussions), this is now the place these questions should be asked (after consulting available documentation).

I will look into Issue templates soon at which point this will be enforced.
