### ISSUE TITLE
Can new functions be added

### ISSUE THREAD

**Issue by gta1005** [HatchesPls/GrandTheftAutoV-Cheat#4]
Can new functions be added
Find a new online session with one click

**Comment by HatchesPls** [comment]
Thank you for the suggestion, it's added to the list! I have to say though, these kind of features do not have the highest priority. New changes for the next features-introducing update are most likely going to be primarily related to existing functionality.

**Comment by HatchesPls** [comment]
Had some spare time, just pushed a commit (e0f3af2f32eff921ec1d0317c700c2a79dafb316) that adds this functionality (Online -> Session).

It's WIP but overall should work fine, will most likely be a while before this is available in a public build. In the meantime you can download and compile it yourself.

**Comment by gta1005** [comment]
> 有一些空闲时间，只是推送了一个添加此功能的提交（[cdfcb2d](https://github.com/HatchesPls/GrandTheftAutoV-Cheat/commit/cdfcb2de52596bbc0471a7e7b98bc71d9878f166)）（在线 -> 会话）。
> 
> 它是 WIP，但总体上应该可以正常工作，很可能需要一段时间才能在公共构建中使用。同时，您可以自己下载和编译。

"New Public" and other functions can be used normally, only "Join Public" cannot be used

**Comment by gta1005** [comment]
> 有一些空闲时间，推送只是一个了添加此功能的提交（[cdfcb2d](https://github.com/HatchesPls/GrandTheftAutoV-Cheat/commit/cdfcb2de52596bbc0471a7e7b98bc71d9878f166)）（在线- >会话）。
> 
> 它是 WIP，但应该可以正常工作，很可能需要在公共场所中使用。同时，您自己下载。

Can you try adding some more features?
such as sending chat messages
