### ISSUE TITLE
spawning car issue

### ISSUE THREAD

**Issue by sean24YT** [HatchesPls/GrandTheftAutoV-Cheat#42]
when spawning a car it throws my car in the sky?
turned option off for spawn air in sky and still happens...

**Comment by HatchesPls** [comment]
Appreciate the report. Is related to https://github.com/HatchesPls/GrandTheftAutoV-Cheat/blob/main/src/game/game.cpp#L162. I did modify that logic not too long ago to ensure no velocity is set (after the 2.2.2.0 release) when spawning without currently being in a vehicle but I will do so affirmative testing to make sure that doesn't happen again.

**Comment by HatchesPls** [comment]
Implemented a proper fix now, will be available in next release (2965791fe676a6bde10ede43f94a91332fd6ca3f)
