### ISSUE TITLE
objective Tp

### ISSUE THREAD

**Issue by sean24YT** [HatchesPls/GrandTheftAutoV-Cheat#48]
when in race with players or in freemode.

no objective or with it will tp me to random player.

**Comment by sean24YT** [comment]
also a bring player would be cool. seems as if all player options dont work after the player is more then like 10 blocks away from your player pos.

**Comment by HatchesPls** [comment]
> when in race with players or in freemode.
> 
> no objective or with it will tp me to random player.

That issue should be resolved in a very recent commit in which I improved objective teleport (067ea5a0c192bb349bcddb4c94d8c7b91009a1d9), this is going live in the next public release.

I noticed issues with some options and player distance too, can you give an example of a feature that doesn't work well when the target player is far away?

**Comment by sean24YT** [comment]
just seen this also this new update is mint,. and yes so if a player is more then around per say for me 4-6 blocks or more options for selected player dont work. such as launch vehicle wich works when close but not when there fair same with pop there tires. for exapmle. if its posible to fix this and make it the intire map worth of rang would be nice. if not also 100% ok. grate work. sorry for spelling!
