### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by 5mdev3** [HatchesPls/GrandTheftAutoV-Cheat#53]
Hi, is there any way to contact you?

**Comment by 5mdev3** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8041	MFC libraries are required for this project. Install them from the Visual Studio installer (Individual Components tab) for any toolsets and architectures being used.	GTAV	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets	483

**Comment by HatchesPls** [comment]
Do as the error message suggests, within the Visual Studio Installer you need to install the MFC C++ library for the given platform version.

**Comment by 5mdev3** [comment]
How would i do that?

**Comment by 5mdev3** [comment]
Or where do i do it?

**Comment by HatchesPls** [comment]
Open the Visual Studio Installer, modify it and make sure the following component is installed. This assumes you use Visual Studio 2022.

![image](https://user-images.githubusercontent.com/86206288/218531306-6f4edf69-3b83-493c-816d-951889c1e229.png)

**Comment by 5mdev3** [comment]
![image](https://user-images.githubusercontent.com/121294497/218532094-6e9ef3a7-ce97-4f37-8131-8efc97e4dce2.png)
Which one would it be?

**Comment by HatchesPls** [comment]
You need to navigate to the Individual components tab and select it from there.

**Comment by 5mdev3** [comment]
Thanks, how do i fix this issue? https://i.imgur.com/d0Sf3KG.png

**Comment by HatchesPls** [comment]
You cannot 'start' a DLL file (using the debugger), which I think is what you are trying to do there. You have to inject the file into the game process using a injector such as [https://github.com/HatchesPls/SimpleModuleInjector](https://github.com/HatchesPls/SimpleModuleInjector).
