### ISSUE TITLE
language

### ISSUE THREAD

**Issue by moonlightlotuos** [HatchesPls/GrandTheftAutoV-Cheat#58]
When I change the language, the menu will be garbled

**Comment by HatchesPls** [comment]
When changing the game language? What language do you use? Could you provide a screenshot of how it exactly looks "garbled"?

**Comment by moonlightlotuos** [comment]
> 什么时候改游戏语言？你用什么语言？你能不能提供一张屏幕截图，说明它研究到底是怎么“乱码”的？
![QQ图片20230224002518](https://user-images.githubusercontent.com/106265222/220969327-40848b38-185f-4c51-aba3-9d806cfb4c7b.png)
![WH27 P1EW)6(SHEGUT_R2HR](https://user-images.githubusercontent.com/106265222/220969336-23c7e57f-7cbe-466a-9e3d-b106ba970b59.png)
Thank you for answering me

**Comment by HatchesPls** [comment]
That is probably because of some kind of encoding issue. I have no experience with Chinese characters and this does fall outside project scope.

If/when this project gets added some kind of language system I will have to figure this out than but for now I unfortunately cannot help with this.
