### ISSUE TITLE
Can new functions be added

### ISSUE THREAD

**Issue by gta1005** [HatchesPls/GrandTheftAutoV-Cheat#6]
Thank you so much for meeting my needs in your busy schedule
"New Public" and other functions can be used normally, only "Join Public" cannot be used
Can you try adding some more features?
such as sending chat messages
For example, I joined a new online conversation and automatically sent the message: "Hi everyone, I'm 007"
Of course I'm just giving an example

**Comment by HatchesPls** [comment]
Just pushed a commit fixing the mention issue with "New Public" (d9b308ec620c7eb31d8134781b6af16a9573c25c). 

Regarding other features like sending chat messages, this is something I will look into in the future.

**Comment by HatchesPls** [comment]
On a closing note; just released version 2.1.0.2 which includes the Join/Change session feature.
